### PR TITLE
Remove legal ES6 keywords from invalid.illegal.js

### PR DESCRIPTION
**Pull request by stevekinney**
`class`, `const`, `export`, `extends`, `import`, and `super` are no longer on [the list of reserved keywords in ES6](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-reserved-words) and they're being used in transpired code these days. So, I think they should be taken off the illegal list.

### CODE REVIEW

**Comment by TheAlphaNerd** [comment]
have you considered a js - next language

One is already available --> https://github.com/Benvie/JavaScriptNext.tmLanguage

Although installation instructions are unclear

**Comment by whitlockjc** [comment]
In my opinion, it would be great to be able to say you're working on browser JavaScript, Node.js JavaScript or some version of JavaScript so that you got warnings/errors where appropriate and didn't just end up with some all encompassing highlighter with nothing more.  I need to talk to @infininight to see what his thoughts are because last time I suggested such a thing, I don't remember why we didn't do it.

What are your thoughts on all of this?  _(This is for all of you involved)_  If we just made the JavaScript syntax assume ES6 or ES5 or whatever, what about those not using that version?  I wish we had some way to tell TextMate that you're using a specific version (browser, node.js, ES*, ...) without having one grammar per because having to toggle between them would become painful.  I'm hoping Michael will chime in with some ideas because if we can come to something, I can do the work in implementing it.

**Comment by chrishiestand** [comment]
I like the jsnext idea. That way when ES6 is official, it can support ES7.

Or at least make a ES6 branch that will eventually become master. Or fork an ES5 branch and update to ES6 now.

**Comment by whitlockjc** [comment]
I'm working on a solution, bear with me.  I need to see if TextMate can do what I'd like before proposing something.

**Comment by chrishiestand** [comment]
Okay, thanks for your labor @whitlockjc

**Comment by JosephPecoraro** [comment]
Any update on this? =)

**Comment by cncolder** [comment]
es6 is not a BREAK update.
beautify-web/js-beautify use the same branch to support es6.
currently, i use a forked version with jsbeautify@1.5.5.

**Comment by stevekinney** [comment]
Just a quick ping. ES2015 has been official for over a year now. I think it would be cool if Textmate didn't make things like `class` as illegal when all of the major browsers now support it.

**Comment by infininight** [comment]
I've now updated the grammar with support for many ES6 features, shouldn't be anything marked illegal any more.

**Pull request closed without merging**
